apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "template.fullname" . }}
  labels:
  {{- include "template.labels" . | nindent 4 }}
data:
  env: {{ .Values.config.env }}
  server-url: {{ .Values.config.serverUrl | quote }}
  client-url: {{ printf "https://%s" .Values.ingress.hostname | quote }}
  graphql-url: {{ .Values.config.backendUrl | quote }}
  version: {{ .Values.frontend.tag | quote }}

  mail: {{ .Values.mail.type | quote }}
  mail-from-name: {{ .Values.mail.from.name | quote }}
  mail-from-email: {{ .Values.mail.from.email | quote }}
  mail-host: {{ .Values.mail.smtp.host | quote }}
  mail-port: {{ .Values.mail.smtp.port | quote }}