apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.settings.name }}
    app.kubernetes.io/part-of: {{ .Values.settings.name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  api-key: {{ .Values.security.apiKey | b64enc | quote }}
  secret: {{ .Values.security.secret | b64enc | quote }}
  pepper: {{ .Values.security.pepper | b64enc | quote }}
  sentry-dns: {{ .Values.security.sentryDns | b64enc | quote }}

  mail-username: {{ .Values.mail.smtp.username | b64enc | quote }}
  mail-password: {{ .Values.mail.smtp.password | b64enc | quote }}

